name: word_quiz
description: Word Quiz Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.19.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockito: ^5.4.5
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  pedantic_mono: any
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  share_plus_platform_interface: ^5.0.2
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/