name: word_quiz
description: Word Quiz Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.3.3
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  hive_generator: ^2.0.1
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  pedantic_mono: any
  plugin_platform_interface: ^2.1.5
  riverpod_generator: ^2.3.6
  share_plus_platform_interface: ^3.3.1
  url_launcher_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/